### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by LeavesEatingCow** [nedlir/languagepod101-scraper#1]
<img width="676" alt="error" src="https://user-images.githubusercontent.com/69094343/100122517-770f9e00-2e47-11eb-995c-e4c262d249ae.PNG">

**Comment by nedlir** [comment]
It seems that you are trying to use the pip module within the python interpreter. 

While you could use pip inside a python code with the sub process module, this is not the "standard" way to install packages. 

Since your screenshot shows that you are using Windows, a simple solution would be:

1. Press Windows+R to open “Run” box. Type “cmd” and then click “OK” to open a regular Command Prompt.

2. Type pip install -r /path_to_requirements_file/requirements.txt

3. Run the code.

**Comment by nedlir** [comment]
It seems that you are trying to use the pip module within the python interpreter.

While you could use pip inside a python code with the sub process module, this is not the "standard" way to install packages.

Since your screenshot shows that you are using Windows, a simple solution would be:

Press Windows+R to open “Run” box. Type “cmd” and then click “OK” to open a regular Command Prompt.

Type "pip install -r /path_to_requirements_file/requirements.txt". 

Run the code.

**Comment by Julian2024** [comment]
can you kindly give a step by step process on how to run the languagepod101 scraper with instructions on what to do, because am having issues running the script. the script runs fine but once you done with entering the user email, password, and ul, it doesnt show where the downloaded file is saved.
